export const POLICY_NAMES = {
  INBOUND_CALL_CONVERSION: "inbound_call_conversion",
  INBOUND_PLACEMENT_RATE: "inbound_placement_rate",
  INBOUND_DAILY_SALES: "inbound_daily_sales_average",
  OUTBOUND_CALL_CONVERSION: "outbound_call_conversion",
  OUTBOUND_PLACEMENT_RATE: "outbound_placement_rate",
  OUTBOUND_DAILY_SALES: "outbound_daily_sales_average",
  HRA: "health_reimbursement_arrangements",
  VBC: "value_based_care",
  REFERRAL_BONUS: "referral_bonus",
  INBOUND_POINT_SCALE: "inbound_point_scale",
  OUTBOUND_POINT_SCALE: "outbound_point_scale",
  INBOUND_SAVES: "inbound_saves",
  OUTBOUND_SAVES: "outbound_saves",
};

export const THRESHOLD_REQUIRED = [
  POLICY_NAMES.OUTBOUND_CALL_CONVERSION,
  POLICY_NAMES.OUTBOUND_PLACEMENT_RATE,
  POLICY_NAMES.OUTBOUND_DAILY_SALES,
  POLICY_NAMES.INBOUND_CALL_CONVERSION,
  POLICY_NAMES.INBOUND_PLACEMENT_RATE,
  POLICY_NAMES.INBOUND_DAILY_SALES,
  POLICY_NAMES.INBOUND_POINT_SCALE,
  POLICY_NAMES.OUTBOUND_POINT_SCALE,
  POLICY_NAMES.INBOUND_SAVES,
  POLICY_NAMES.OUTBOUND_SAVES,
];

export const FIELD_REQUIRED = [
  POLICY_NAMES.OUTBOUND_CALL_CONVERSION,
  POLICY_NAMES.OUTBOUND_PLACEMENT_RATE,
  POLICY_NAMES.OUTBOUND_DAILY_SALES,
  POLICY_NAMES.INBOUND_CALL_CONVERSION,
  POLICY_NAMES.INBOUND_PLACEMENT_RATE,
  POLICY_NAMES.INBOUND_DAILY_SALES,
  POLICY_NAMES.HRA,
  POLICY_NAMES.VBC,
  POLICY_NAMES.REFERRAL_BONUS,
  POLICY_NAMES.INBOUND_POINT_SCALE,
  POLICY_NAMES.OUTBOUND_POINT_SCALE,
  POLICY_NAMES.INBOUND_SAVES,
  POLICY_NAMES.OUTBOUND_SAVES,
];
